name: 'Soteria'
description: 'Tool for Insecure Communication Linting'
inputs:
  project-path:  # Project Path
    description: 'Path of Project to Lint'
    required: true
    default: ''
outputs:
  lint-logs:
    description: "Linting Logs"
    value: ${{ steps.soteria-tool.outputs.lint-logs }}
runs:
  using: "composite"
  steps:
    - name: Set Project Path
      run: echo "Hello $INPUT_PROJECT_PATH"
      shell: bash
      env:
        INPUT_PROJECT_PATH: ${{ inputs.project-path }}

    - name: Generate Logs
      id: soteria-tool
      run: echo "lint-logs=$(echo $LOGS)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run Soteria
      run: ls
      shell: bash
