name: 'Soteria'
description: 'Tool for Insecure Communication Linting'
inputs:
  project-path: # Project Path
    description: 'Location of Project'
    required: true
  use-bashfile: # Use Bash File Static Analyzer
    description: 'Used to Disable Bash Analyzer'  
    required: true
    default: false
  use-makefile: # Use Makefile Static Analyzer
    description: 'Used to Disable Makefile Analyzer'  
    required: true
    default: false
  use-dockerfile: # Use Dockerfile Static Analyzer
    description: 'Used to Disable Dockerfile Analyzer'  
    required: true
    default: false
outputs:
  logs:
    description: 'Logging Output'
    value: ${{ steps.run-soteria.outputs.logs }}
runs:
  using: composite
  steps:
  - uses: actions/setup-go@v2
    with:
      go-version: 'go 1.21.6'

  - name: Run Soteria
    id: run-soteria
    run: |
      cd Soteria/Soteria/
      ./Soteria
